version: '3'
services:
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "berbasov_test_db"
    networks:
      backend:
        - aliases:
            - "db"
  configserver:
    build: ./configserver/
    container_name: "config"
    ports:
      - "8051:8051"
    networks:
      backend:
        - aliases:
            - "config-server"

  users-service:
    build: ./users-service/
    container_name: "users"
    ports:
      - "8081:8081"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 20s

  statistics-service:
    build: ./statistics-service/
    container_name: "stats"
    ports:
      - "8082:8082"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 20s


networks:
  backend:
    driver: bridge