spring:
  application:
    name: users-service
#  config:
#    import: optional:configserver:http://configserver:8051
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        show_sql: true