spring:
  application:
    name: stat-service
  config:
#    import: configserver:http://localhost:8051
    import: configserver:http://configserver:8051
  profiles:
#    active: test
    active: dock

