#spring:
#  application:
#    name: statistics-service
#  config:
#    import: configserver:http://configserver:8051
server:
  port: 8081
spring:
  application:
    name: stat-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        show_sql: true